#!/bin/bash

echo "🔧 SimpleChatプロジェクトのリンカーフラグを修正します..."
echo ""
echo "Xcodeで以下の手順を実行してください："
echo ""
echo "1. SimpleChatプロジェクトを選択"
echo "2. SimpleChatターゲットを選択"
echo "3. Build Settingsタブを開く"
echo "4. 'Other Linker Flags'を検索"
echo "5. 以下のフラグを追加："
echo ""
echo "   -Wl,-all_load"
echo "   -lmlc_llm"
echo "   -lmodel_iphone"
echo "   -ltvm_runtime"
echo "   -ltokenizers_cpp"
echo "   -lsentencepiece"
echo "   -ltokenizers_c"
echo ""
echo "6. 'Library Search Paths'に以下を追加："
echo "   /Users/agmajima/Downloads/mlc-llm/ios/MLCChat/dist/lib"
echo ""
echo "これにより、MLCの初期化関数が正しくリンクされます。"